# Generated by Django 3.0.6 on 2021-03-26 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210326_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='Thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Tut_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 26, 16, 54, 18, 774716), verbose_name='date published'),
        ),
    ]
